---

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Include:
    - Rakefile
    - config.ru
    - app/**/*
    - lib/**/*
    - confg/**/*

  Exclude:
    - db/schema.rb
    - vendor/**/*
    - app/views/**/*
    - app/assets/**/*

Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Layout/LineLength:
  Max: 120
Lint/MissingSuper:
  Exclude:
    - app/abilities/*
