name: Rubocop

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruby:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Rubocop Check
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
